spring:
  profiles: local
  application:
    name: web_test_demo
  #===============
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/localtest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: hntywork

  redis:  # 单机
    host: 127.0.0.1
    port: 6379
    maxWaitMillis: 1000   #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    password:
    testOnBorrow: true   #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    database: 2
    testWhileIdle: true   #每次释放连接的最大数目,默认3
    maxIdle: 30   #最大空闲数
    minEvictableIdleTimeMillis: 300000   #连接的最小空闲时间 默认1800000毫秒(30分钟)
    timeBetweenEvictionRunsMillis: 30000   #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    maxTotal: 1000   #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    timeout: 10000  #客户端超时时间单位是毫秒 默认是2000
    numTestsPerEvictionRun: 1024
##==========================
mybatis-plus:
  type-aliases-package: [com.unicorn.unicornmultitest] #entity vo dto 的扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #mybatis-plus配置控制台打印完整带参数SQL语句
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1  #逻辑删除值，默认值1
      logic-notdelete-value: 0 #逻辑未删除值，默认值0

server:
  port: 8080